# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official lightweight Node.js image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript application
RUN npm run build

# Use a separate runtime container to keep it lightweight
FROM node:18-alpine AS runner

WORKDIR /app

# Copy the built files from the builder
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Set environment variable for production
ENV NODE_ENV=production

# Install only production dependencies
RUN npm ci --only=production

# Run the application
ENTRYPOINT ["node", "dist/index.js"]
